name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user/golang-backend
          
          git pull origin master
          
          sudo pkill main || true
          sudo fuser -k 4040/tcp || true
          sleep 2
          
          mkdir -p /home/ec2-user/golang-backend/storage
          chmod 755 /home/ec2-user/golang-backend/storage

          CGO_ENABLED=1 go build -o main cmd/backend/main.go
          
          nohup ./main -config config/local.yaml > output.log 2>&1 &