name: Deploy Go Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t iharshyadav/backend-go:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push iharshyadav/backend-go:${{ github.sha }}

      - name: Tag Latest
        run: |
          docker tag iharshyadav/backend-go:${{ github.sha }} iharshyadav/backend-go:latest
          docker push iharshyadav/backend-go:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: |
          set -x
          docker pull iharshyadav/backend-go:latest

      - name: Stop and Remove Old Container
        run: |
          set -x
          docker rm -f go-app-container || true

      - name: Run New Container
        run: |
          set -x
          docker run -d -p 4040:4040 \
            --name go-app-container \
            -v /home/ubuntu/actions-runner/_work/backend-go/backend-go/config:/app/config \
            iharshyadav/backend-go:latest \
            --config config/local.yaml
